***************
*** 664,672 ****
  %-show-tag:
         @$(LINUXKIT) pkg show-tag pkg/$*
  
- %Gopkg.lock: %Gopkg.toml | $(GOBUILDER)
-        @$(DOCKER_GO) "dep ensure -update $(GODEP_NAME)" $(dir $@)
-        @echo Done updating $@
  
  docker-old-images:
         ./tools/oldimages.sh
--- 666,674 ----
  %-show-tag:
         @$(LINUXKIT) pkg show-tag pkg/$*
  
+ #%Gopkg.lock: %Gopkg.toml | $(GOBUILDER)
+ #      @$(DOCKER_GO) "dep ensure -update $(GODEP_NAME)" $(dir $@)
+ #      @echo Done updating $@
  
  docker-old-images:
         ./tools/oldimages.sh
